const ACCESS_SECRET = process.env.ACCESS_SECRET
const REFRESH_SECRET = process.env.REFRESH_SECRET
const MONGO_URL = process.env.MONGO_URL
const GOOGLE_CLIENT_ID = process.env.GOOGLE_CLIENT_ID
const GOOGLE_CLIENT_SECRET = process.env.GOOGLE_CLIENT_SECRET
const F2A_SECRET = process.env.F2A_SECRET
export { 
    ACCESS_SECRET, 
    REFRESH_SECRET,
    MONGO_URL, 
    GOOGLE_CLIENT_SECRET,
    GOOGLE_CLIENT_ID,
    F2A_SECRET
}