version: '3.8'

services:
  client:
    build: 
      context: ./client
      dockerfile: dev.Dockerfile
    env_file:
      - ./client/.env
    ports:
      - 5173:5173
    volumes:
      - ./client:/app
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./server:/app
    env_file:
      - ./server/.env
    depends_on:
      redis-stack:
        condition: service_started  
  redis-stack:
    image: redis:7.2.4-alpine3.19
    container_name: redis
   

      
  
   